
trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  buildNumber: '0.0.0'

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: 
    checkLatest: true

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: PowerShell@2
  inputs:
    filePath: 'assemblyversion.ps1'
    arguments: '$(buildNumber)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# - task: CopyFiles@2
#   inputs:
#     SourceFolder: '$(build.sourcesDirectory)/Maverick.PCF.Builder'
#     Contents: 'ReleaseNotes.txt'
#     TargetFolder: '$(Build.ArtifactStagingDirectory)'

# - task: CopyFiles@2
#   inputs:
#     SourceFolder: '$(build.sourcesDirectory)'
#     Contents: 'PCF-CustomControlBuilder.nuspec'
#     TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(build.sourcesDirectory)/Maverick.Xrm.DependencyIdentifier/bin/Release'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/DependencyIdentifier/bin/Release'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'buildfiles'
    publishLocation: 'Container'
