
trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  buildNumber: '0.0.0'

steps:
- task: NuGetToolInstaller@1
  displayName: 'NuGet Installer'
  inputs:
    versionSpec: 
    checkLatest: true

- task: NuGetCommand@2
  displayName: 'Restore NuGet packages'
  inputs:
    restoreSolution: '$(solution)'

- task: PowerShell@2
  displayName: 'Update Version'
  inputs:
    filePath: '.build/assemblyversion.ps1'
    arguments: '$(buildNumber)'

- task: VSBuild@1
  displayName: 'Build Solution'
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  displayName: 'Test Solution'
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# - task: CopyFiles@2
#   inputs:
#     SourceFolder: '$(build.sourcesDirectory)/Maverick.PCF.Builder'
#     Contents: 'ReleaseNotes.txt'
#     TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: CopyFiles@2
  displayName: 'Copy NuGet packaging file'
  inputs:
    SourceFolder: '$(build.sourcesDirectory)/.build'
    Contents: 'DependencyIdentifier.nuspec'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: CopyFiles@2
  displayName: 'Copy plugin files'
  inputs:
    SourceFolder: '$(build.sourcesDirectory)/Maverick.Xrm.DependencyIdentifier/bin/Release'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/DependencyIdentifier/bin/Release'

- task: PublishBuildArtifacts@1
  displayName: 'Publish build files to Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'buildfiles'
    publishLocation: 'Container'
